using Microsoft.EntityFrameworkCore;
using GeekStore.Infrastructure.Data;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddDbContext<GeekStoreDbContext>(options =>
    options.UseNpgsql("Host=localhost;Database=geekstore_db;Username=postgres;Password=postgres"));

using var host = builder.Build();
using var scope = host.Services.CreateScope();
var db = scope.ServiceProvider.GetRequiredService<GeekStoreDbContext>();

Console.WriteLine("Creating Disputes table...");
var sql = @"
    CREATE TABLE IF NOT EXISTS ""Disputes"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""OrderId"" integer NOT NULL,
        ""InitiatorUserId"" integer NOT NULL,
        ""TargetUserId"" integer NOT NULL,
        ""Reason"" character varying(1000) NOT NULL,
        ""Status"" character varying(50) NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""AdminResolution"" character varying(1000) NULL,
        CONSTRAINT ""PK_Disputes"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_Disputes_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES ""Orders"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_Disputes_Users_InitiatorUserId"" FOREIGN KEY (""InitiatorUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_Disputes_Users_TargetUserId"" FOREIGN KEY (""TargetUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
    );
";
await db.Database.ExecuteSqlRawAsync(sql);
Console.WriteLine("Table created successfully (if it didn't exist).");
