#if DEBUG
using GoblinSpot.Core.Entities;
using GoblinSpot.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoblinSpot.Api.Controllers
{
    /// <summary>
    /// Controlador de desarrollo para regenerar datos de prueba después de
    /// la migración de SQLite → PostgreSQL.
    ///
    /// ⚠️ SOLO PARA DESARROLLO. Eliminar o proteger antes de producción.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Authorize(Roles = "Admin")]
    public class SeedController : ControllerBase
    {
        private readonly GoblinSpotDbContext _db;

        public SeedController(GoblinSpotDbContext db)
        {
            _db = db;
        }

        [HttpPost("create-disputes-table")]
        public async Task<IActionResult> CreateDisputesTable()
        {
            var sql = @"
                CREATE TABLE IF NOT EXISTS ""Disputes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""OrderId"" integer NOT NULL,
                    ""InitiatorUserId"" integer NOT NULL,
                    ""TargetUserId"" integer NOT NULL,
                    ""Reason"" character varying(1000) NOT NULL,
                    ""Status"" character varying(50) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""AdminResolution"" character varying(1000) NULL,
                    CONSTRAINT ""PK_Disputes"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Disputes_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES ""Orders"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Disputes_Users_InitiatorUserId"" FOREIGN KEY (""InitiatorUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Disputes_Users_TargetUserId"" FOREIGN KEY (""TargetUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ";
            await _db.Database.ExecuteSqlRawAsync(sql);
            return Ok(new { message = "Disputes table created" });
        }

        [HttpPost("create-refunds-table")]
        public async Task<IActionResult> CreateRefundsTable()
        {
            // Add ResolvedAt column to Disputes if missing
            await _db.Database.ExecuteSqlRawAsync(@"
                ALTER TABLE ""Disputes"" ADD COLUMN IF NOT EXISTS ""ResolvedAt"" timestamp with time zone NULL;
            ");

            await _db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""Refunds"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""DisputeId"" integer NOT NULL,
                    ""BeneficiaryUserId"" integer NOT NULL,
                    ""Amount"" numeric NOT NULL,
                    ""Status"" character varying(50) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ProcessedAt"" timestamp with time zone NULL,
                    ""Notes"" character varying(500) NULL,
                    CONSTRAINT ""PK_Refunds"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Refunds_Disputes_DisputeId"" FOREIGN KEY (""DisputeId"") REFERENCES ""Disputes"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Refunds_Users_BeneficiaryUserId"" FOREIGN KEY (""BeneficiaryUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ");
            return Ok(new { message = "Refunds table and Disputes.ResolvedAt column created" });
        }

        [HttpPost("create-user-blocks-table")]
        public async Task<IActionResult> CreateUserBlocksTable()
        {
            await _db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""UserBlocks"" (
                    ""BlockerId"" integer NOT NULL,
                    ""BlockedUserId"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_UserBlocks"" PRIMARY KEY (""BlockerId"", ""BlockedUserId""),
                    CONSTRAINT ""FK_UserBlocks_Blocker"" FOREIGN KEY (""BlockerId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_UserBlocks_Blocked"" FOREIGN KEY (""BlockedUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ");
            return Ok(new { message = "UserBlocks table ready." });
        }

        [HttpPost("add-2fa-columns")]
        public async Task<IActionResult> Add2FAColumns()
        {
            await _db.Database.ExecuteSqlRawAsync(@"
                ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""TwoFactorEnabled"" boolean NOT NULL DEFAULT false;
                ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""TwoFactorSecret"" character varying(64) NULL;
                ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""TwoFactorBackupCodes"" character varying(1000) NULL;
            ");
            return Ok(new { message = "2FA columns added to Users table." });
        }

        [HttpPost("add-listing-type-column")]
        public async Task<IActionResult> AddListingTypeColumn()
        {
            await _db.Database.ExecuteSqlRawAsync(@"
                ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""ListingType"" varchar(10) NOT NULL DEFAULT 'Sale';
            ");
            return Ok(new { message = "ListingType column added to Products." });
        }

        [HttpPost("create-product-reports-table")]
        public async Task<IActionResult> CreateProductReportsTable()
        {
            await _db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""ProductReports"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProductId"" integer NOT NULL,
                    ""ReporterUserId"" integer NOT NULL,
                    ""ReasonCategory"" character varying(100) NOT NULL,
                    ""Details"" character varying(1000) NULL,
                    ""Status"" character varying(50) NOT NULL DEFAULT 'Pending',
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    ""ReviewedAt"" timestamp with time zone NULL,
                    ""AdminNotes"" character varying(500) NULL,
                    CONSTRAINT ""PK_ProductReports"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ProductReports_Products"" FOREIGN KEY (""ProductId"") REFERENCES ""Products"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ProductReports_Users"" FOREIGN KEY (""ReporterUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""UQ_ProductReports_Reporter_Product"" UNIQUE (""ReporterUserId"", ""ProductId"")
                );
            ");
            return Ok(new { message = "ProductReports table ready." });
        }

        /// <summary>
        /// POST /api/seed
        /// Regenera usuarios de prueba, productos de ejemplo y una orden de demostración.
        /// Requiere que la base de datos ya tenga las categorías sembradas por la migración.
        /// </summary>
        [HttpPost]
        public async Task<ActionResult> SeedDatabase()
        {
            // ── 1. Verificar que no se ejecute sobre datos existentes ────────
            if (await _db.Users.AnyAsync())
                return BadRequest("La base de datos ya contiene datos. Limpia antes de re-sembrar.");

            // ── 2. Usuarios de Prueba ────────────────────────────────────────
            var admin = new User
            {
                Name = "Super",
                Surname = "Admin",
                Nickname = "goblin-admin",
                Email = "admin@goblinspot.com",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("admin123"),
                Role = "Admin",
                IsActive = true,
                IsVerified = true,
                PhoneNumber = "+50688887777"
            };

            var seller1 = new User
            {
                Name = "Carlos",
                Surname = "Ramírez",
                Nickname = "DragonTrader",
                Email = "carlos@test.com",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("test123"),
                Role = "Seller",
                IsActive = true,
                IsVerified = true,
                PhoneNumber = "+50687654321",
                SubscriptionPlan = "Licencia Mercante",
                SubscriptionEndDate = System.DateTime.UtcNow.AddDays(30),
                AutoRenew = true
            };

            var seller2 = new User
            {
                Name = "María",
                Surname = "López",
                Nickname = "MagicQueen",
                Email = "maria@test.com",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("test123"),
                IsActive = true,
                IsVerified = true,
                PhoneNumber = "+50611223344",
                SubscriptionPlan = "Licencia de Prueba",
                SubscriptionEndDate = System.DateTime.UtcNow.AddMinutes(-1), // Expired! Worker should catch this
                AutoRenew = false
            };

            var buyer = new User
            {
                Name = "Luis",
                Surname = "Fernández",
                Nickname = "GoblinBuyer",
                Email = "luis@test.com",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("test123"),
                Role = "Buyer",
                IsActive = true,
                IsVerified = true,
                PhoneNumber = "+50699998888"
            };

            _db.Users.AddRange(admin, seller1, seller2, buyer);
            await _db.SaveChangesAsync();

            // ── 3. Productos de Ejemplo ──────────────────────────────────────
            var products = new List<Product>
            {
                new Product
                {
                    SellerId = seller1.Id,
                    CategoryId = 5, // Cartas Sueltas (sub de TCG)
                    Name = "Black Lotus (Proxy NM)",
                    Description = "Proxy de alta calidad del icónico Black Lotus de Alpha. Ideal para casual play.",
                    PriceCRC = 15000,
                    ImageUrl = "https://cards.scryfall.io/large/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7571.jpg",
                    StockStatus = "Available",
                    StockCount = 2,
                    Condition = "NM"
                },
                new Product
                {
                    SellerId = seller1.Id,
                    CategoryId = 5,
                    Name = "Lightning Bolt (4th Edition)",
                    Description = "Carta clásica de Magic: The Gathering en buen estado.",
                    PriceCRC = 3500,
                    ImageUrl = "https://cards.scryfall.io/large/front/f/2/f29ba16f-c8fb-42fe-aabf-87089cb214a7.jpg",
                    StockStatus = "Available",
                    StockCount = 8,
                    Condition = "LP"
                },
                new Product
                {
                    SellerId = seller1.Id,
                    CategoryId = 6, // Cajas Selladas
                    Name = "Booster Box - Aetherdrift",
                    Description = "Caja sellada de 36 sobres de la última expansión de MTG.",
                    PriceCRC = 85000,
                    ImageUrl = "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=400&q=80",
                    StockStatus = "Available",
                    StockCount = 3,
                    Condition = "M"
                },
                new Product
                {
                    SellerId = seller2.Id,
                    CategoryId = 8, // Anime (sub de Figuras)
                    Name = "Figura Goku Ultra Instinct 25cm",
                    Description = "Figura de acción de Dragon Ball Super. Articulada, base incluida.",
                    PriceCRC = 28000,
                    ImageUrl = "https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=400&q=80",
                    StockStatus = "Available",
                    StockCount = 1,
                    Condition = "M"
                },
                new Product
                {
                    SellerId = seller2.Id,
                    CategoryId = 9, // Funko Pop
                    Name = "Funko Pop! Pikachu #353",
                    Description = "Funko Pop de Pokémon, edición regular. Caja en perfecto estado.",
                    PriceCRC = 12000,
                    ImageUrl = "https://images.unsplash.com/photo-1609372332255-611485350f25?w=400&q=80",
                    StockStatus = "Available",
                    StockCount = 4,
                    Condition = "NM"
                },
                new Product
                {
                    SellerId = seller2.Id,
                    CategoryId = 13, // Manga (sub de Cómics)
                    Name = "Manga One Piece Vol. 1-5 Bundle",
                    Description = "Tomos 1 al 5 de One Piece en español. Lomo con uso mínimo.",
                    PriceCRC = 22000,
                    ImageUrl = "https://images.unsplash.com/photo-1613376023733-0a73315d9b06?w=400&q=80",
                    StockStatus = "Available",
                    StockCount = 1,
                    Condition = "LP"
                },
                new Product
                {
                    SellerId = seller1.Id,
                    CategoryId = 10, // Consolas Retro
                    Name = "Game Boy Advance SP (AGS-101)",
                    Description = "Consola Game Boy Advance SP con pantalla retroiluminada. Funcional.",
                    PriceCRC = 45000,
                    ImageUrl = "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?w=400&q=80",
                    StockStatus = "Available",
                    StockCount = 1,
                    Condition = "MP"
                },
                new Product
                {
                    SellerId = seller1.Id,
                    CategoryId = 7, //  Accesorios TCG
                    Name = "Deck Box Ultra Pro (Satin Tower)",
                    Description = "Caja para mazos con compartimento para dados. Color negro.",
                    PriceCRC = 9500,
                    ImageUrl = "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&q=80",
                    StockStatus = "Available",
                    StockCount = 6,
                    Condition = "M"
                }
            };

            _db.Products.AddRange(products);
            await _db.SaveChangesAsync();

            // ── 4. Orden de Ejemplo ──────────────────────────────────────────
            var sampleOrder = new Order
            {
                BuyerId = buyer.Id,
                SellerId = seller1.Id,
                TotalAmountCRC = 18500, // Black Lotus + Lightning Bolt
                Status = "Pending",
                DeliveryMethod = "Pickup",
                OrderDate = DateTime.UtcNow.AddDays(-1)
            };
            _db.Orders.Add(sampleOrder);
            await _db.SaveChangesAsync();

            var orderItems = new List<OrderItem>
            {
                new OrderItem { OrderId = sampleOrder.Id, ProductId = products[0].Id, Quantity = 1, UnitPriceCRC = 15000 },
                new OrderItem { OrderId = sampleOrder.Id, ProductId = products[1].Id, Quantity = 1, UnitPriceCRC = 3500 }
            };
            _db.OrderItems.AddRange(orderItems);
            await _db.SaveChangesAsync();

            // Order buyer -> seller2 (so buyer can review seller2 too)
            var sampleOrder2 = new Order
            {
                BuyerId = buyer.Id,
                SellerId = seller2.Id,
                TotalAmountCRC = 28000,
                Status = "Completed",
                DeliveryMethod = "Pickup",
                OrderDate = DateTime.UtcNow.AddDays(-3),
                ConfirmedAt = DateTime.UtcNow.AddDays(-3).AddHours(1),
                ShippedAt = DateTime.UtcNow.AddDays(-2),
                CompletedAt = DateTime.UtcNow.AddDays(-1)
            };
            _db.Orders.Add(sampleOrder2);
            await _db.SaveChangesAsync();

            var orderItems2 = new List<OrderItem>
            {
                new OrderItem { OrderId = sampleOrder2.Id, ProductId = products[3].Id, Quantity = 1, UnitPriceCRC = 28000 }
            };
            _db.OrderItems.AddRange(orderItems2);
            await _db.SaveChangesAsync();

            // ── 5. Reseñas de Ejemplo ────────────────────────────────────────
            var reviews = new List<Review>
            {
                new Review
                {
                    ReviewerId = buyer.Id,
                    SellerId = seller1.Id,
                    Rating = 5,
                    Comment = "Excelente vendedor, las cartas llegaron en perfectas condiciones. ¡100% recomendado!",
                    CreatedAt = DateTime.UtcNow.AddDays(-1)
                },
                new Review
                {
                    ReviewerId = buyer.Id,
                    SellerId = seller2.Id,
                    Rating = 4,
                    Comment = "Muy buena figura, empaque seguro. El envío tardó un poco pero todo bien.",
                    CreatedAt = DateTime.UtcNow.AddDays(-2)
                }
            };
            _db.Reviews.AddRange(reviews);
            await _db.SaveChangesAsync();

            // ── 6. Notificaciones de Ejemplo ──────────────────────────────────
            var notifications = new List<Notification>
            {
                new Notification
                {
                    UserId = buyer.Id,
                    Title = $"Orden #{sampleOrder2.Id} completada",
                    Message = $"MagicQueen ha marcado tu orden #{sampleOrder2.Id} (₡28,000) como completada.",
                    Type = "OrderUpdate",
                    RelatedEntityId = sampleOrder2.Id,
                    IsRead = true,
                    CreatedAt = DateTime.UtcNow.AddDays(-1)
                },
                new Notification
                {
                    UserId = seller1.Id,
                    Title = "Nueva orden recibida",
                    Message = $"GoblinBuyer ha realizado una orden #{sampleOrder.Id} por ₡18,500. Revisa tu panel de órdenes.",
                    Type = "OrderUpdate",
                    RelatedEntityId = sampleOrder.Id,
                    IsRead = false,
                    CreatedAt = DateTime.UtcNow.AddDays(-1)
                },
                new Notification
                {
                    UserId = seller2.Id,
                    Title = "Nueva reseña recibida",
                    Message = "GoblinBuyer te ha dejado una reseña de 4 estrellas. ¡Revisa tu perfil!",
                    Type = "ReviewReceived",
                    IsRead = false,
                    CreatedAt = DateTime.UtcNow.AddDays(-2)
                }
            };
            _db.Notifications.AddRange(notifications);
            await _db.SaveChangesAsync();

            return Ok(new
            {
                message = "✅ Base de datos sembrada exitosamente",
                users = new[] { admin.Email, seller1.Email, seller2.Email, buyer.Email },
                password = "test123 (admin: admin123)",
                productsCreated = products.Count,
                ordersCreated = 2,
                reviewsCreated = reviews.Count,
                notificationsCreated = notifications.Count,
                hint = "Usa POST /api/seed/reset para limpiar y volver a sembrar."
            });
        }

        /// <summary>
        /// POST /api/seed/reset
        /// Limpia TODOS los datos y vuelve a sembrar desde cero.
        /// ⚠️ DESTRUCTIVO - Solo para desarrollo.
        /// </summary>
        [HttpPost("reset")]
        public async Task<ActionResult> ResetAndSeed()
        {
            // Limpiar en orden de dependencias (FK)
            _db.Notifications.RemoveRange(_db.Notifications);
            _db.Reviews.RemoveRange(_db.Reviews);
            _db.OrderItems.RemoveRange(_db.OrderItems);
            _db.Orders.RemoveRange(_db.Orders);
            _db.UserFollows.RemoveRange(_db.UserFollows);
            _db.Products.RemoveRange(_db.Products);
            _db.Users.RemoveRange(_db.Users);
            await _db.SaveChangesAsync();

            // Delegar la re-siembra al endpoint principal
            return await SeedDatabase();
        }
    }
}
#endif
