// <auto-generated />
using System;
using GeekStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekStore.Infrastructure.Migrations
{
    [DbContext(typeof(GeekStoreDbContext))]
    [Migration("20260311204231_AddProductCondition")]
    partial class AddProductCondition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("GeekStore.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TCG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Figuras"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Videojuegos"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cómics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cartas Sueltas",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cajas Selladas",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accesorios TCG",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anime",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Funko Pop",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Consolas Retro",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Juegos Físicos",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Marvel",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 13,
                            Name = "Manga",
                            ParentId = 4
                        });
                });

            modelBuilder.Entity("GeekStore.Core.Entities.DeliveryPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPoints");
                });

            modelBuilder.Entity("GeekStore.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredDeliveryPointId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceCRC")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreferredDeliveryPointId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GeekStore.Core.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "SellerMonthlyFee",
                            Value = "1.00"
                        });
                });

            modelBuilder.Entity("GeekStore.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeekStore.Core.Entities.Category", b =>
                {
                    b.HasOne("GeekStore.Core.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GeekStore.Core.Entities.Product", b =>
                {
                    b.HasOne("GeekStore.Core.Entities.DeliveryPoint", "PreferredDeliveryPoint")
                        .WithMany()
                        .HasForeignKey("PreferredDeliveryPointId");

                    b.HasOne("GeekStore.Core.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredDeliveryPoint");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("GeekStore.Core.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
